image: node:16

pipelines:
  branches:
    master:
      - step:
          name: Install Dependencies & Build Project
          size: 2x
          caches:
            - node
          script:
            - cd client
            - npm install --legacy-peer-deps
            - CI=false npm run build
            - cd ../
          artifacts:
            - build/**
      - step:
          name: Deploy to master
          script:
            - scp -pvr build/* cbdev@147.182.160.178:/var/www/html/tokenmaker